# Generated by Django 6.0.3 on 2026-04-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_equipo_id_alter_estado_id_alter_etiqueta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='tareas.equipo'),
        ),
    ]
