# Generated by Django 6.0.3 on 2026-04-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_estado_equipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together={('equipo', 'nombre')},
        ),
    ]
