# Generated by Django 6.0.3 on 2026-04-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_alter_estado_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='estado',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados', to='tareas.equipo'),
        ),
    ]
